version: '3.8'

services:
  webapp:
    build: .
    volumes:
      - ./web_application:/app/web_application
    ports:
      - '3000:3000'
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
