version: '3.8'

services:
  webapp:
    build: .
    volumes:
      - ./storage:/data
    ports:
      - '3000:3000'
      - '5000:5000'
    environment:
      - MONGO_PASSWORD=your_mongo_password
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'

volumes:
  mongo_data:
    driver: local
