version: '3.8'

services:
  webapp:
    build: .
    volumes:
      - ./web_application:/app
      - ./storage:/app/storage
    ports:
      - '3000:3000'
      - '6000:6000'
    environment:
      - MONGO_PASSWORD=your_mongo_password
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
